version: 2.1
orbs:
  # basic actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.0

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      # install node, checkout and yarn
      - node/install
      - checkout
      - node/install-yarn:
          version: 1.22.4
      - aws-cli/setup
      - eb/setup
      - run:
          # Install front-end dependencies
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          # Install Backend-end dependencies
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          # Build front-end app
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name:
            Back-End Build
            # Build backend-end api
          command: |
            npm run backend:build
      - run:
          # deploy both front and back end
          name: front-end & back-End Deploy
          command: |
            npm run deploy

workflows:
  build_and_deploy:
    jobs:
      - build:
        filters:
          branches:
            only:
              - main
              - master
